#!/bin/csh
#
# 0) Be sure to use C-shell and source this file every time you login. For example your .tcshrc 
#    will contain the command "source /usr/local/GMTSAR/gmtsar_config".  Start a new shell to be sure this
#    file is sourced properly.
#
#****************************************************************************
#  INSTALLATION INSTRUCTIONS - START
#
# 1) First type the commands "uname -p" and "uname -m" on your computer.  Uncomment the appropriate command.
# 
#setenv OS `uname -m`
setenv OS `uname -p`
#
# 2) Set the compiler switch to match the way GMT was compiled 32 or 64 bit
#
setenv M64 "-m64 -O3 "
setenv mt "-mt"
#setenv M64 "-m32 -O3"
#
# 3) Set the path to GMT, NETCDF,  and GMTSAR
#    (Find the files libnetcdf.a and libgmt.a on your computer)
#
setenv GMTHOME /opt/local/lib/gmt4
setenv NETCDFHOME /opt/local
setenv GMTSARHOME /usr/local/GMTSAR
#
# For fink try the following. Make sure you have the gmt-dev and netcdf-dev installed.
#
# setenv GMTHOME /sw
# setenv NETCDFHOME /sw
#
#  don't change the next line
#
setenv GMTSAR $GMTSARHOME/gmtsar
#
# 4) set path to orbit directory
#
setenv ORBITS /usr/local/orbits
#
# 5) Set the cfft1d routine for your computer
#
#
# A.  no special fft code is available
#
#cd $GMTSAR/lib_src
#rm cfft1d.c
#ln -s cfft1d_codes/cfft1d_fftpack.c cfft1d.c
#cd ../..
#
# B. optional for mac using veclib. 
#
#rm -f $GMTSAR/lib_src/cfft1d.c
#ln -s $GMTSAR/lib_src/cfft1d_codes/cfft1d_veclib.c $GMTSAR/lib_src/cfft1d.c
setenv VEC "-framework Accelerate"
#
# C. optional fftw (not tested yet)
#
#rm $GMTSAR/lib_src/cfft1d.c
#ln -s $GMTSAR/lib_src/cfft1d_codes/cfft1d_fftw.c $GMTSAR/lib_src/cfft1d.c
#
#  INSTALLATION INSTRUCTIONS - END
#****************************************************************************
#
#  Set the paths for running the code. Don't change these lines.
#
#
if !($?PATH) then
    setenv PATH $GMTSAR/bin:$GMTSAR/csh:$GMTSARHOME/preproc/bin
else
    setenv PATH $GMTSAR/bin:$GMTSAR/csh::$GMTSARHOME/preproc/bin:$PATH
endif
#
